AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    32f67558-019e-4f79-bd15-525359e48798:
      size:
        width: 60
        height: 60
      position:
        x: -160.60651740719766
        'y': -899.5500559708664
      z: 0
Resources:
  S3B44QSG:
    Type: 'AWS::S3::Bucket'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 32f67558-019e-4f79-bd15-525359e48798
